#pragma once
namespace OBJ
{//모습가릴떄 여기 순서바꿔보자
	enum ID{ UIBACK, HYPERSKILL,ATTMON,MONSKILL, RANSHOT,BOOM,LIGHTAIR,GUN, BULLET,RIGINGSHOT,JACKSPIKE,CROSS,FLASHMINE,NEIPHAMTAN,BUSTER,FLASHER,FLEEZER,C4,FLAMESHOT, UI4, UI5, UI6,UI7,UI8, MONSTER, NILLSNA , PLAYER , FLAMEBULLET,  UI, UI2, UI3 , MOUSE,END, };
}
namespace PLAYER
{
	enum State{LEFT,RIGHT,JUMP,IDLE};
}
namespace PLAYERJS
{
	enum State2 { LEFT, RIGHT, IDLE};
}
namespace BULLET
{
	enum DIR { LEFT, RIGHT };
}
namespace BULLET2
{
	enum DIR { LEFT, RIGHT };
}

namespace MONSTER
{
	enum State { LEFT, RIGHT,JUMP,IDLE	};
}namespace MONSTER2
{
	enum State2 { IDLE, ATT, PAIN,SKILL, BOOM,LIGHT,RANSHOT, DIE };
}